# Generated by Django 4.2.10 on 2024-03-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('ip', models.CharField(max_length=64, verbose_name='IP-адрес сервера')),
                ('port', models.PositiveIntegerField(verbose_name='TCP/IP-порт сервера (1025..65635)')),
                ('proxy_type', models.CharField(choices=[('FTP', 'ftp'), ('CGI', 'cgi'), ('SMPT, POP3, IMAP', 'smtp, pop3, imap'), ('HTTP, HTTPS', 'http, https'), ('SOCKS', 'socks')], default='HTTP, HTTPS', max_length=64)),
                ('login', models.CharField(max_length=256, verbose_name='Логин')),
                ('password', models.CharField(max_length=256, verbose_name='Пароль')),
                ('country', models.CharField(max_length=256, verbose_name='Страна')),
                ('available', models.BooleanField(verbose_name='Доступность')),
            ],
            options={
                'verbose_name': 'Прокси сервер',
                'verbose_name_plural': 'Прокси серверы',
            },
        ),
    ]
