# Generated by Django 4.2.10 on 2024-03-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=256, verbose_name='Имя хоста')),
                ('address', models.CharField(max_length=256, verbose_name='Адрес хоста')),
                ('port', models.PositiveIntegerField(verbose_name='TCP/IP-порт хоста (1025..65635)')),
                ('type', models.CharField(choices=[('FTP', 'ftp'), ('CGI', 'cgi'), ('SMPT, POP3, IMAP', 'smtp, pop3, imap'), ('HTTP, HTTPS', 'http, https'), ('SOCKS', 'socks')], default='HTTP, HTTPS', max_length=64, verbose_name='Тип')),
                ('username', models.CharField(blank=True, max_length=256, null=True, verbose_name='Логин')),
                ('password', models.CharField(blank=True, max_length=256, null=True, verbose_name='Пароль')),
                ('country_code', models.CharField(blank=True, max_length=2, null=True, verbose_name='Код страны')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
                ('is_available', models.BooleanField(default=False, verbose_name='Доступен')),
            ],
            options={
                'verbose_name': 'Прокси сервер',
                'verbose_name_plural': 'Прокси серверы',
            },
        ),
    ]
