# Generated by Django 4.2.10 on 2024-03-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxyserver',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='proxyserver',
            name='available',
            field=models.BooleanField(default=False, verbose_name='Доступность'),
        ),
        migrations.AlterField(
            model_name='proxyserver',
            name='country',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Страна'),
        ),
    ]
