# Generated by Django 4.2.10 on 2024-03-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_server', '0002_alter_proxyserver_active_alter_proxyserver_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxyserver',
            name='country',
            field=models.CharField(choices=[('RU', 'ru'), ('US', 'us'), ('UK', 'uk'), ('CN', 'cn'), ('CA', 'ca'), ('EU', 'eu'), ('AU', 'au')], default='EU', max_length=256, verbose_name='Страна'),
        ),
    ]
